<?php
if (eregi("page_development.php",$PHP_SELF)) {
  Header("Location: index.php");
  die();
}
?>

<H4>Development</H4>

<p>This page contains informations and instructions on how-to setup your environment if you want to contribute to the Firebird Core Engine.</p>

<p><H5><a name="tools"></a>Used tools</H5>

If you want to contribute to the Firebird Core Engine Project, there are several tools that you have to install and configure. The first program you need is an CVS client which allows you to check out the latest version of the Firebird sources (if you want to actively contribute please ask in the <a href="index.php?op=lists#fb-devel" target="_blank" title="Firebird-devel Mailinglist">&quot;firebird-devel&quot;</a> mailing list for code review and for CVS write access). Next you need the C compiler (GCC for *nix or VC >=5 for Windows). Please <b>always</b> refer to the platform-related documents distributed with Firebird sources (in build_docs subdirectory) for detailed and up-to-date information about the version of C compiler, additional tools and environment setup requied for sucessful compilation from sources on your platform.</p>

<p>The usual Firebird compilation process require running Firebird/InterBase on build machine. If you can't afford this prerequisite (for example, you're going to port Firebird to new platform), you also need the fresh <b>Firebird bootkit</b>. The bootkit contains preparsed C files that are used in place of those generated by an existing system.  These "bootstrap" the build. The boot build kit should be available from our website, or you can ask for the fresh one in firebird-devel mailing list.
</p>

<H5><a name="environment"></a>Environment setup</H5>

Here are the steps you need to perform before actually can check out, edit and compile the Firebird:
<ul>
  <li>Download and install your favorite CVS utility. I recommend <a href="http://www.wincvs.org/download.html" target="_blank" title="WinCVS download">WinCVS</a>. For Linux you don't need any client software because CVS support should be included in your distribution.</li>
</ul>
<p>After you are done with the installations you have to start your CVS client and check-out the modul "interbase" or "Firebird2" from the Sourceforge CVS repository. Please refer to our <A href="index.php?op=devel&id=cvs_howto">CVS How To</A> for detailed instructions.
</p>

<p><H5><a name="compiling"></a>Compiling the sources</H5>
<b>NOTE:</b> If you use CVS to checked out the source make a backup copy of the original source checkout. If you muck up the build and want to start again it is easiest to restore from this original backup file (This is due to a weakness in the way the current build process works).
</p>

<p><b>Unix - Firebird 1</b><br>
Now open the prompt (terminal window) and change to the folder where you checked out the &quot;interbase&quot; module. Configure the build system for DEV (debug) or PROD (production) build
<pre>
$./Configure.sh DEV|PROD [system]
</pre>
where "system" is one from AIX, AP, AX, DELTA, DG, EPSON, HP700, HP800, HP9.0, HP10, IMP, MU, SCO, SGI, SOLARIS, SUN4, UNIXWARE, AIX_PPC, LINUX, FREEBSD, NETBSD, DARWIN.</p>
<p>
setup environment variables required for compilation
<pre>
$source Configure_SetupEnv.sh
</pre>
Build either CLASSIC or SUPER architectures.
<pre>
$make firebird            -- for classic version 
# OR
$make super_firebird      -- for super version.
</pre>
</p>
<p><b>Windows - Firebird 1</b><br>
Under construction...
</p>
<p><b>Unix - Firebird 2</b><br>
The Firebird 2 build process is built on Autoconf, so usual ./Configure, make, make install should work for you.
</p>
<p><b>Windows - Firebird 2</b><br>
Under construction...
</p>

<p>
<H5><a name="deploying"></a>Deploying the compiled files</H5>

<p><b>Unix - Firebird 1</b><br>
On any Unix based system, the usual make install should work for you. You can also use "classicrpmfile", "classictarfile", "superrpmfile", "supertarfile" or "clasicpackages" and "superpackages" make targets to build distributable packages (tar.gz, rpm or both) without actually installing compiled Firebird to your build machine.
</p>
<p><b>Windows - Firebird 1</b><br>
Under construction...
</p>
<p><b>Unix - Firebird 2</b><br>
The Firebird 2 build process is built on Autoconf, so usual make install should work for you.
</p>
<p><b>Windows - Firebird 2</b><br>
Under construction...
</p>

<H5><a name="contribute"></a>Contribute to the Firebird Core Engine Project</H5>

If you want to join the Firebird team you have to do next things:<br>
<ol>
  <li>Take your time to watch the traffic in <a href="index.php?op=lists#fb-devel" target="_blank" title="Firebird-devel Mailinglist">&quot;firebird-devel&quot;</a> mailing list for awhile until you will not get comfortable with our development efforts, structure, process and future plans.</li>
  <li>Choose your working area:
    <ul>
      <li>You can join one of our development drifts.</li>
      <li>You can <A href="index.php?op=devel&id=bugdb">choose a bug</A> to fix it.</li>
      <li>You can propose and design a new feature. It's better to consult it in <A href="index.php?op=lists#ib-architect">IB-Architect</A> mailing list first.</li>
    </ul>
  </li>
  <li>
    Post in the <a href="index.php?op=lists#fb-devel" target="_blank" title="Firebird-devel Mailinglist">&quot;firebird-devel&quot;</a> mailing list about your intention, area of development and how you want to implement it.</li>
  <li>Ask for code review for your patch.</li>
  <li>If you have at least one patch accepted, and you want to continue your work on Firebird Core Engine, you can ask for CVS write access.</li>
</ol>

<H5><a name="guidelines"></a>Coding standards and guidelines</H5>
Under construction...

<p><H5><a name="faq"></a>Frequently Asked Questions</H5>

They will follow as soon as someone has asked something.</p>

<p><H5><a name="additional"></a>Additional informations and resources</H5>

If you have any suggestions or criticism please drop us an e-mail in <a href="index.php?op=lists#fb-devel" title="Firebird-devel Mailinglist">&quot;firebird-devel&quot;</a> mailing list.</p>

<p>
Back to <A href="index.php?op=devel&amp;sub=engine">Core Engine Project</A>.
<p>